# Database configuration
db_host = db
db_port = 5432
db_user = odoo
db_password = 1casTaño1
db_name = odoo_db

# Security
admin_passwd = 1casTaño1

# Addons path
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons

# Data and Logging
data_dir = /var/lib/odoo
log_level = info